publish_frequency: 1.0
update_frequency: 4.0
width: 5.0
height: 5.0
resolution: .025
global_frame: odom
robot_base_frame: base_link
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
rolling_window: true
plugins:
 # - {name: static_map, type: "costmap_2d::StaticLayer"}
 - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
 - {name: inflater, type: "costmap_2d::InflationLayer"}
obstacles:
    observation_sources: /scan
    /scan: {data_type: LaserScan, sensor_frame: /base_laser_link, expected_update_rate: 0.3, marking: true, clearing: true}
